### PR TITLE
Chrome support

### PR DESCRIPTION
**Pull request by aminya**
In chrome, it says that `player.showControl` is not a function! I am not sure why it says that because the function exists and this works perfectly in firefox.

This does not affect Firefox functionality at all (even speeds-up loading performance).

### CODE REVIEW

**Comment by nralbrecht** [comment]
Hi, thanks for your work! This is looking very good.
It currently still works on my Firefox.

Regarding Chrome not knowing the `player.showControls` method: This is an issue regarding sand boxing. In Firefox you can access the Js object with [`player.wrappedJSObject`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/wrappedJSObject) and call the methods on the underling object.

Chrome is far more aggressive with their sand boxing and, as far as I know, does not allow for this. The only way a interact with the Js objects, is to inject a script and [communicate](https://developer.chrome.com/extensions/content_scripts#host-page-communication) with it.
Do you want to work on that?

Aside from that, I am curious what you need the `@types/chrome` dependency for.

**Comment by aminya** [comment]
> Hi, thanks for your work! This is looking very good.

You're welcome!

> It currently still works with my Firefox.
> 
> Regarding Chrome not knowing the `player.showControls` method: This is an issue regarding sand boxing. In Firefox you can access the Js object with [`player.wrappedJSObject`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/wrappedJSObject) and call the methods on the underling object.
> 
> Chrome is far more aggressive with their sand boxing and, as far as I know, does not allow for this. The only way a interact with the Js objects, is to inject a script and [communicate](https://developer.chrome.com/extensions/content_scripts#host-page-communication) with it.
> Do you want to work on that?
> 

I did not know about this. I am not familiar with injecting a script. How should we do that?

> Aside from that, I am curious what you need the `@types/chrome` dependency for.

In my IDE, that helps autocompletion. For example, when I write `chrome.`, it gives me all the available API.

**Comment by nralbrecht** [comment]
> I did not know about this. I am not familiar with injecting a script. How should we do that?

By creating a script tag and communicating with it. Have a look at [this stackoverflow question](https://stackoverflow.com/questions/3955803/chrome-extension-get-page-variables-in-content-script).

> In my IDE, that helps autocompletion. For example, when I write `chrome.`, it gives me all the available API.

Interesting. What IDE do u use?

**Comment by aminya** [comment]
> > I did not know about this. I am not familiar with injecting a script. How should we do that?
> 
> By creating a script tag and communicating with it. Have a look at [this stackoverflow question](https://stackoverflow.com/questions/3955803/chrome-extension-get-page-variables-in-content-script).
> 

Thanks. That's useful.

> > In my IDE, that helps autocompletion. For example, when I write `chrome.`, it gives me all the available API.
> 
> Interesting. What IDE do u use?

Jetbrains Webstorm. However, I think most of the IDEs should be the same in this regard. Webstorm uses a TypeScript language server protocol to serve JavaScript code.

**Comment by nralbrecht** [comment]
> Thanks. That's useful.

You're welcome! Let me know if I can help you.

**Comment by nralbrecht** [comment]
I had some time on my hands and fixed the discussed permission problem.

**Comment by aminya** [comment]
Awesome!

**Comment by nralbrecht** [comment]
The chrome extention is currently pending review. I will post the link once it's available.

**Comment by nralbrecht** [comment]
Published extention in the Chrome webstore: [https://chrome.google.com/webstore/detail/hide-youtube-fullscreen-c/akkdefghgcakdgkmakeajmijjhlcofmk](https://chrome.google.com/webstore/detail/hide-youtube-fullscreen-c/akkdefghgcakdgkmakeajmijjhlcofmk)

**Pull request merged**
